baseURL = "https://syntacticnacl.com/"
languageCode = "en-us"
paginate = 5
publishDir="docs"
title = "syntacticNaCl.com | Hi, I am syntacticNaCl"
googleAnalytics="UA-35798055-2"
copyright = "2021"

[languages]
  [languages.en]
    title = "syntacticNaCl.com | Hi, I am syntacticNaCl"
    description="Hi, I am Garrett (aka syntacticNaCl). I am a software engineer who loves to tinker, play table-top games, read, and break things"
    keywords = "syntacticNaCl, engineer, hacker, terminal, table-top, software, web"
    copyright = "2021"
    menuMore = "Show more"
    writtenBy = "Written by"
    readMore = "Read more"
    readOtherPosts = "Read other posts"
    newerPosts = "Newer posts"
    olderPosts = "Older posts"
    minuteReadingTime = "min read"
    dateFormatSingle = "2006-01-02"
    dateFormatList = "2006-01-02"
    # leave empty to disable, enter display text to enable
    # lastModDisplay = ""

    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "about"
        name = "About"
        url = "/about"
      [[languages.en.menu.main]]
        identifier = "showcase"
        name = "Showcase"
        url = "/showcase"
